introduce anyhow, introduce graphml writeout, move away from karajou
paritytech/cargo-unleash pull request #59
Opened 2021-11-22 14:47 UTC by drahnr

A coalescation that is yet to be split into three individual ones

* `fn toposort` detects cycles in graphs when there are none, a diamond is not a cycle. Using `fn kosaraju_scc` instead, which provides the same as well as the cycles which helps debugging
* move to `anyhow` (or `eyre`, TBD) - the error handling before was not really intuitive
* write a `graphml` (or `graphviz`, TBD) to a file, this has to be refactored in a subcommand

The motivation behind this was a major PITA releasing `juice` on the weekhand which has such diamond shape dependencies, and no info on where the supposedly existent cycles exist.

2021-11-23 11:34 UTC, drahnr commented
Defering the impl of the `graphviz` generation due to the plethora of libs that do partial impls, `petgraph-graphml` is far from perfect without digging deep into spec, the commits should be atomic and reviewable.

2021-11-23 18:11 UTC, drahnr commented
Verifying the cycles, it shows that the detected ones are bogus. This leads me a bit in the direction that the graph is actually constructed not quite right.

2021-11-24 15:08 UTC, drahnr commented
> Verifying the cycles, it shows that the detected ones are bogus. This leads me a bit in the direction that the graph is actually constructed not quite right.

This was an issue that got introduced in the first commit, extracting the `Workspace`, but the follow up closure `maybe_patch` which removes the `DevDependencies` section, was hence not read. The last commit resolves this and no more cycles are detected.

2021-11-24 17:24 UTC, gnunicorn requested changes
Very nice, thanks! The dot-visualisations are a nice new features!

Just two request:
1. do you mind adding a test case showing the problem and that it is resolved with this PR? I honestly am not the best crack re graphiz and want to make sure that we have a test case ensuring we don't introduce regressions upon this later!
2. please add this and the new dot-visualisation-feature to the Changelog! That's soo cool!

2021-11-29 16:21 UTC, drahnr commented
Tests are bit messy, but there doesn't seem to be any released cargo test helper create that is released. Changelog was updated :)

2021-11-29 16:22 UTC, drahnr commented
And rebased.

2021-11-30 11:17 UTC, gnunicorn approved these changes
Nice! thanks!

2021-11-30 11:17 UTC, gnunicorn commented on src/commands/to_release.rs
> +mod tests {
we usually use actual fixtures and cli-e2e tests for cases this complicated, but this is fine, too...!

2021-11-30 11:23 UTC, merged